version: '3'
services:
  server:
    image: digdag
    ports:
      - "65432-65433:65432-65433"
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/opt/digdag/logs
      - ./database:/opt/digdag/database
  client:
    image: digdag
    volumes:
      - .:/project
      - /tmp:/tmp
    working_dir: /project
    command: digdag
    links:
      - server
